spring:
  application:
    name: MeokPlaylist

  datasource:
    url: jdbc:mysql://localhost:3306/noshow2025?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: noshow2025
    password: 2025
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4

  flyway:
    enabled: true          # default: true
    baseline-on-migrate: true  # 기존 테이블이 있어도 1회차부터 진행
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: update  # Entity 기반으로 table 생성
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  defer-datasource-initialization: true #이거 필수띠

  sql:
    init:
      mode: always



server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
cloud:
  ncp:
    object-storage:
      access-key: ncp_iam_BPAMKR3RB01iniV2T75P
      secret-key: ncp_iam_BPKMKRCaBvaLBbnEhWbbR56ueQNlOYfWnn
      endpoint: https://kr.object.ncloudstorage.com
      bucket: testmeokplaylist

oauth:
  google:
    client-id: 614172335108-a6j4nkrudna9k8tpon4anj3jgi6ee0ts.apps.googleusercontent.com
