spring:
  application:
    name: MeokPlaylist

  datasource:
    url: jdbc:mysql://localhost:3306/noshow2025?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: noshow2025
    password: 2025
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration

cloud:
  ncp:
    object-storage:
      access-key: ncp_iam_BPAMKR3RB01iniV2T75P
      secret-key: ncp_iam_BPKMKRCaBvaLBbnEhWbbR56ueQNlOYfWnn
      endpoint: https://kr.object.ncloudstorage.com
      bucket: testmeokplaylist

oauth:
  google:
    client-id: 614172335108-a6j4nkrudna9k8tpon4anj3jgi6ee0ts.apps.googleusercontent.com


kakao:
  local:
    base-url: https://dapi.kakao.com
    rest-api-key: d8fd3cc299e7921ad9cbce305123c7a8

tourapi:
  base-url: https://apis.data.go.kr/B551011/TarRlteTarService1
  service-key: 57edced7cc0621ce34923583294e68b55c6e8fcc22d7c91e2048879aa9ea6202
  mobile-os: ETC
  mobile-app: MeokPlaylist
  default-type: json
  connect-timeout-ms: 2000
  read-timeout-ms: 3000

rsa:
  private-key-path: keys/private.pem
  public-key-path: keys/public.pem