spring:
  application:
    name: MeokPlaylist

  datasource:
    url: jdbc:postgresql://dpg-d30phk7diees73876th0-a:5432/meokplaylistDb
    username: meokplaylistdb_user
    password: mJnQZQ7bs3RpY800MS9DKuLgSUSGqlqZ
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true    # default: true
    baseline-on-migrate: true  # 기존 테이블이 있어도 1회차부터 진행
    locations: classpath:db/migration


  defer-datasource-initialization: true #이거 필수띠
  sql:
    init:
      mode: always


server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
cloud:
  ncp:
    object-storage:
      access-key: ncp_iam_BPAMKR3RB01iniV2T75P
      secret-key: ncp_iam_BPKMKRCaBvaLBbnEhWbbR56ueQNlOYfWnn
      endpoint: https://kr.object.ncloudstorage.com
      bucket: testmeokplaylist

oauth:
  google:
    client-id: 614172335108-a6j4nkrudna9k8tpon4anj3jgi6ee0ts.apps.googleusercontent.com


rsa:
  private-key-path: keys/private.pem
  public-key-path: keys/public.pem

kakao:
  local:
    base-url: https://dapi.kakao.com
    rest-api-key: d8fd3cc299e7921ad9cbce305123c7a8

tourapi:
  base-url: https://apis.data.go.kr/B551011/TarRlteTarService1
  service-key: 57edced7cc0621ce34923583294e68b55c6e8fcc22d7c91e2048879aa9ea6202
  mobile-os: ETC
  mobile-app: MeokPlaylist
  default-type: json
  connect-timeout-ms: 2000
  read-timeout-ms: 3000

tourapi2:
  base-url: https://apis.data.go.kr/B551011/KorPetTourService
  service-key: 57edced7cc0621ce34923583294e68b55c6e8fcc22d7c91e2048879aa9ea6202


