spring:
  application:
    name: MeokPlaylist

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  defer-datasource-initialization: true
  sql:
    init:
      mode: always

cloud:
  ncp:
    object-storage:
      access-key: ${NCP_ACCESS_KEY}
      secret-key: ${NCP_SECRET_KEY}
      endpoint: https://kr.object.ncloudstorage.com
      bucket: ${NCP_BUCKET}

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}

kakao:
  local:
    base-url: https://dapi.kakao.com
    rest-api-key: ${KAKAO_REST_KEY}

tourapi:
  base-url: https://apis.data.go.kr/B551011/TarRlteTarService1
  service-key: ${TOURAPI_KEY}
  mobile-os: ETC
  mobile-app: MeokPlaylist
  default-type: json
  connect-timeout-ms: 2000
  read-timeout-ms: 3000


rsa:
  private-key-path: /etc/secrets/private.pem
  public-key-path: /etc/secrets/public.pem
